/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presintationmohamadghaneem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class changePassword extends javax.swing.JPanel {
    public static Connection con;
    /**
     * Creates new form changePassword
     */
    public changePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        old = new javax.swing.JPasswordField();
        ne = new javax.swing.JPasswordField();
        cnew = new javax.swing.JPasswordField();
        l = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        old.setBackground(new java.awt.Color(255, 255, 255));
        old.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        old.setForeground(new java.awt.Color(102, 0, 0));
        add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 230, 50));

        ne.setBackground(new java.awt.Color(255, 255, 255));
        ne.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ne.setForeground(new java.awt.Color(102, 0, 0));
        add(ne, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 230, 50));

        cnew.setBackground(new java.awt.Color(255, 255, 255));
        cnew.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cnew.setForeground(new java.awt.Color(102, 0, 0));
        cnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnewKeyReleased(evt);
            }
        });
        add(cnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 230, 50));

        l.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        l.setForeground(new java.awt.Color(204, 0, 0));
        l.setText("                ");
        add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 440, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/confirm.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 160, 90));

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 18, 6));
        jLabel3.setText("Royal Cars");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 300, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 300, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/27640edit05-Recovered-Recovdfdered_1 (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{if(ne.getText().equals(cnew.getText())){
           String a="";
            l.setText("Password does match");
        Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sql = "SELECT * FROM manager WHERE pass = ?";        
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1,old.getText());
    ResultSet rs = ps.executeQuery();
       int c=0;
    while (rs.next())
    {c++;
    a=rs.getString("remmber");
    }
    if(c!=0){//موجود
         try {
              Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
           String string="delete from manager where pass=?";
           PreparedStatement s=con.prepareStatement(string);
           s.setString(1,old.getText());
           s.execute();
           l.setText("Done *_*");
            String sn = "INSERT INTO manager(pass,sec_pass,id,remmber) VALUES(?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sn);
            stmt.setString(1,ne.getText());
            stmt.setString(2,"1232001");
            stmt.setString(3,"201810990"); 
            stmt.setString(4,a); 
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Saved");

        } catch (Exception ex) {
        } 
        
    }else{
        //الباسوورد القديم خاطئ
        l.setText("Wrong old password!");
    }
       } else{
           l.setText("Password does not match"); 
       }
       }catch(Exception e){
        
    }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cnewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnewKeyReleased
    if(!ne.getText().equals(cnew.getText())){
      l.setText("Password does not match");
    }else
      l.setText("Password does match");  
    }//GEN-LAST:event_cnewKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnew;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l;
    private javax.swing.JPasswordField ne;
    private javax.swing.JPasswordField old;
    // End of variables declaration//GEN-END:variables
}
