/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presintationmohamadghaneem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class changCarStatus extends javax.swing.JPanel {
    public static Connection con;

    /**
     * Creates new form changCarStatus
     */
    public changCarStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        stat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("    Car status change");

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 18, 6));
        jLabel2.setText("Royal Cars");

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter Licence Plate :");

        p.setBackground(new java.awt.Color(255, 255, 255));
        p.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        p.setForeground(new java.awt.Color(102, 0, 0));
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pKeyTyped(evt);
            }
        });

        stat.setBackground(new java.awt.Color(255, 255, 255));
        stat.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        stat.setForeground(new java.awt.Color(102, 0, 0));
        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Effective", "In repairs" }));

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Chose the status of the car:");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyTyped
if(p.getText().length()>=7)
evt.consume();
// TODO add your handling code here:
    }//GEN-LAST:event_pKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{if(exist(p.getText())){
            String[]arr=new String[11];
             Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sql = "SELECT * FROM car WHERE lic_plate=?";        
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1,p.getText());
    ResultSet rs = ps.executeQuery();
    boolean flag =false;
    while (rs.next())
    {
        if(rs.getString("status").equals("rented"))
            flag=true;
    arr[0]=rs.getString("name");
    arr[1]=rs.getString("company");
    arr[2]=rs.getString("fax_num");
    arr[3]=rs.getString("type");
    arr[4]=rs.getString("lic_plate");
    arr[5]=rs.getString("ensurance");
    arr[6]=stat.getSelectedItem().toString();
    arr[7]=rs.getString("color");
    arr[8]=rs.getString("description");
    arr[9]=rs.getString("price");
    arr[10]=rs.getString("year_manu");
    }
           //حدف سيارة
           String string="delete from car where lic_plate=?";
           PreparedStatement s=con.prepareStatement(string);
           s.setString(1,p.getText());
           s.execute();
           //اضافه سيارة
           String sl = "INSERT INTO car(name,company,fax_num,type,lic_plate,ensurance,status,color,description,price,year_manu) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sl);
            stmt.setString(1,arr[0]);
            stmt.setString(2,arr[1]);
            stmt.setString(3,arr[2]);
            stmt.setString(4,arr[3]);
            stmt.setString(5,arr[4]);
            stmt.setString(6,arr[5]);
            stmt.setString(7,arr[6]);
            stmt.setString(8,arr[7]);
            stmt.setString(9,arr[8]);
            stmt.setString(10,arr[9]);
            stmt.setString(11,arr[10]);
            stmt.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Done *_- ");
            if(flag&&id()!=null){
                ////
                   String[]use=new String[14];
    String sq = "SELECT * FROM user WHERE user_id=?";        
    PreparedStatement ps1 = con.prepareStatement(sq);
    ps1.setString(1,id());
    ResultSet rs1 = ps1.executeQuery();
    while (rs1.next())
    {
        String li=rs1.getString("licence");
        if(li.equals(p.getText())&&rs1.getString("stat").equals("no")){
    use[0]=rs1.getString("name");
    use[1]=rs1.getString("age");
    use[2]=rs1.getString("user_id");
    use[3]=rs1.getString("phone");
    use[4]=rs1.getString("licence");
    use[5]=rs1.getString("address");
    use[6]=rs1.getString("received_data");
    use[7]=rs1.getString("lease");
    use[8]=rs1.getString("discount");
    use[9]=rs1.getString("pay_method");
    use[10]=rs1.getString("chek_num");
    use[11]=rs1.getString("receive_chek");
    use[12]=rs1.getString("amount");
    use[13]="yes";
    }}
    //حدف اليوزر
    String stringu="delete from user where user_id=? AND licence=? AND stat=?";
           PreparedStatement su=con.prepareStatement(stringu);
           su.setString(1,id());
           su.setString(2, p.getText());
           su.setString(3, "no");
           su.execute();
    
    // اضافه اليوزر     
    String sul = "INSERT INTO user(name,age,user_id,phone,licence,address,received_data,lease,discount,pay_method,chek_num,receive_chek,amount,stat) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stmtu = con.prepareStatement(sul);
            stmtu.setString(1,use[0]);
            stmtu.setString(2,use[1]);
            stmtu.setString(3,use[2]);
            stmtu.setString(4,use[3]);
            stmtu.setString(5,use[4]);
            stmtu.setString(6,use[5]);
            stmtu.setString(7,use[6]);
            stmtu.setString(8,use[7]);
            stmtu.setString(9,use[8]);
            stmtu.setString(10,use[9]);
            stmtu.setString(11,use[10]);
            stmtu.setString(12,use[11]);
            stmtu.setString(13,use[12]);
            stmtu.setString(14,use[13]);
            stmtu.executeUpdate();
            }
    }else
        JOptionPane.showMessageDialog(null, "The car licence plate does not exist");
        }catch(Exception e){
             
         }
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public boolean exist(String s){
    try{ 
        Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sql = "SELECT * FROM car WHERE lic_plate=?";        
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1,s);

    ResultSet rs = ps.executeQuery();
    while (rs.next())
    {return true;
    } 
    return false;
    }catch(Exception e){
        
    }
    return false;
}
public String id(){
  try{
      Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sq = "SELECT * FROM user WHERE licence=? AND stat=?";        
    PreparedStatement ps1 = con.prepareStatement(sq);
    ps1.setString(1,p.getText());
    ps1.setString(2,"no");
    ResultSet rs1 = ps1.executeQuery();
    while (rs1.next())
    {
        String li=rs1.getString("user_id");
        return li;
        
    }
    return null;
  }  
    catch(Exception e){
      
  }
  return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField p;
    private javax.swing.JComboBox<String> stat;
    // End of variables declaration//GEN-END:variables
}
