/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presintationmohamadghaneem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class enterUser extends javax.swing.JPanel {
public static Connection con;

    /**
     * Creates new form enterUser
     */
    public enterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        lic_num = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        leas = new javax.swing.JTextField();
        ch_num = new javax.swing.JTextField();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        year = new javax.swing.JTextField();
        pay = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        age = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        discount = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(102, 0, 0));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 50));

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(102, 0, 0));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 190, 50));

        phone.setBackground(new java.awt.Color(255, 255, 255));
        phone.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(102, 0, 0));
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 50));

        lic_num.setBackground(new java.awt.Color(255, 255, 255));
        lic_num.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lic_num.setForeground(new java.awt.Color(102, 0, 0));
        lic_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lic_numKeyTyped(evt);
            }
        });
        add(lic_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 190, 50));

        adress.setBackground(new java.awt.Color(255, 255, 255));
        adress.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adress.setForeground(new java.awt.Color(102, 0, 0));
        add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 190, 50));

        data.setBackground(new java.awt.Color(255, 255, 255));
        data.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        data.setForeground(new java.awt.Color(102, 0, 0));
        add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 190, 50));

        leas.setBackground(new java.awt.Color(255, 255, 255));
        leas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        leas.setForeground(new java.awt.Color(102, 0, 0));
        leas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leasMouseEntered(evt);
            }
        });
        leas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                leasKeyTyped(evt);
            }
        });
        add(leas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 190, 50));

        ch_num.setBackground(new java.awt.Color(255, 255, 255));
        ch_num.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ch_num.setForeground(new java.awt.Color(102, 0, 0));
        ch_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ch_numKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ch_numKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ch_numKeyReleased(evt);
            }
        });
        add(ch_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 190, 50));

        day.setBackground(new java.awt.Color(255, 255, 255));
        day.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        day.setForeground(new java.awt.Color(102, 0, 0));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 70, 40));

        month.setBackground(new java.awt.Color(255, 255, 255));
        month.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        month.setForeground(new java.awt.Color(102, 0, 0));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 70, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        year.setForeground(new java.awt.Color(102, 0, 0));
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yearKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pay.setForeground(new java.awt.Color(102, 0, 0));
        pay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Check" }));
        add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 190, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 210, 50));

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 18, 6));
        jLabel2.setText("Royal Cars");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 300, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 320, 10));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        age.setBackground(new java.awt.Color(255, 255, 255));
        age.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        age.setForeground(new java.awt.Color(102, 0, 0));
        age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 370, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        discount.setBackground(new java.awt.Color(255, 255, 255));
        discount.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        discount.setForeground(new java.awt.Color(102, 0, 0));
        discount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 200, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("**discount percentage");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 160, -1));

        jLabel5.setText("  ");
        jLabel5.setToolTipText("According to the number of rental days");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 160, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/clears.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/add.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 350, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/27640edit05-Recovered-Recovereood.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void ch_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ch_numKeyTyped
   if(ch_num.getText().length()<8){
        char c = evt.getKeyChar();
      if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
         evt.consume();  // ignore event
      
   }} else
        evt.consume(); 
   // TODO add your handling code here:
    }//GEN-LAST:event_ch_numKeyTyped

    private void yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyTyped
if(year.getText().length()<4){
        char c = evt.getKeyChar();
      if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
         evt.consume();  // ignore event
      
   }}else
      evt.consume();     
// TODO add your handling code here:
    }//GEN-LAST:event_yearKeyTyped

    private void ch_numKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ch_numKeyPressed

    }//GEN-LAST:event_ch_numKeyPressed

    private void ch_numKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ch_numKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_numKeyReleased

    private void leasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leasKeyTyped
 char c = evt.getKeyChar();
      if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
         evt.consume();  // ignore event
      
   }         // TODO add your handling code here:
    }//GEN-LAST:event_leasKeyTyped

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
 if(phone.getText().length()<10){
        char c = evt.getKeyChar();
      if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
         evt.consume();  // ignore event
      
   } }else 
      evt.consume();
     // TODO add your handling code here:
    }//GEN-LAST:event_phoneKeyTyped

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
    if(id.getText().length()<9){
        char c = evt.getKeyChar();
      if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
         evt.consume();  // ignore event
      
   } }else 
      evt.consume();    // TODO add your handling code here:
    }//GEN-LAST:event_idKeyTyped

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(pay.getSelectedItem().toString().equals("Check")){
        if(isNotEmptyChek()){
        if(validDate(Integer.parseInt(day.getSelectedItem().toString()), Integer.parseInt(month.getSelectedItem().toString()), Integer.parseInt(year.getText().toString()))){
        if(validReturnCheck(Integer.parseInt(day.getSelectedItem().toString()), Integer.parseInt(month.getSelectedItem().toString()), Integer.parseInt(year.getText().toString()))){
            if(chekPhone(phone.getText())){
               if(id.getText().length()==9){
                 if(ch_num.getText().length()==8){
                   if(NotrepeatID()){
                      if(NotrepeatChek()){
                          if(repeatLic_plate()!=null){
                              if(chekCar()){
                              String price=repeatLic_plate();
                          ///code
                          try{
                            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String s = "INSERT INTO user(name,age,user_id,phone,licence,address,received_data,lease,discount,pay_method,chek_num,receive_chek,amount,stat) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(s);
            stmt.setString(1,name.getText());
            stmt.setString(2, age.getSelectedItem().toString());
            stmt.setString(3, id.getText());
            stmt.setString(4, phone.getText());
            stmt.setString(5, lic_num.getText());
            stmt.setString(6, adress.getText().toString());
            stmt.setString(7, data.getText().toString());
            stmt.setString(8, leas.getText());
            stmt.setString(9, discount.getSelectedItem().toString());
            stmt.setString(10, pay.getSelectedItem().toString());
            stmt.setString(11, ch_num.getText());
            String s1=day.getSelectedItem().toString()+"/"+month.getSelectedItem().toString()+"/"+year.getText();
            stmt.setString(12,s1);
            int dis=Integer.parseInt(discount.getSelectedItem().toString());
            price=((Integer.parseInt(price)*Integer.parseInt(leas.getText()))-((Integer.parseInt(price)*Integer.parseInt(leas.getText()))*dis/100))+"";             
            stmt.setString(13,price);
            stmt.setString(14,"no");
            stmt.executeUpdate();
            editCarStatus();
            String show="saved *_- \nthe price is : "+price;
            JOptionPane.showMessageDialog(this,show);
                          }catch(Exception e){
                              System.out.println(e);
                          }}else
                             JOptionPane.showMessageDialog(null, "The car is not available");     
                          }else
                             JOptionPane.showMessageDialog(null, "The Licence number is not available at the store");  
                      }else
                          JOptionPane.showMessageDialog(null, "The check number should not be repeated");
                   }else
                       JOptionPane.showMessageDialog(null, "The ID number is duplicated but not for the same person");
                   
                     
                 } 
                 else
                   JOptionPane.showMessageDialog(null, "There is an error in the Check number");    
                   
               } else
              JOptionPane.showMessageDialog(null, "There is an error in the ID number");     
              
            }else{
                JOptionPane.showMessageDialog(null, "There is an error in the phone number");
            }
        }else{
            JOptionPane.showMessageDialog(null, "There is an error in the check cashing date"); 
        }
    }else{
        JOptionPane.showMessageDialog(null, "There is an error in the check cashing date");   
    }
        }else
             JOptionPane.showMessageDialog(null, "One of the fields is empty"); 
            }
    
    
    else{
        if(isNotEmptyCash()){
     if(chekPhone(phone.getText())){
            if(id.getText().length()==9){
               if(NotrepeatID()){
              if(repeatLic_plate()!=null){
                  if(chekCar()){
                              String price=repeatLic_plate();
                              
                          ///code
                          
                          try{
                            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String s = "INSERT INTO user(name,age,user_id,phone,licence,address,received_data,lease,discount,pay_method,amount,stat) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(s);
            stmt.setString(1,name.getText());
            stmt.setString(2, age.getSelectedItem().toString());
            stmt.setString(3, id.getText());
            stmt.setString(4, phone.getText());
            stmt.setString(5, lic_num.getText());
            stmt.setString(6, adress.getText().toString());
            stmt.setString(7, data.getText().toString());
            stmt.setString(8, leas.getText());
            stmt.setString(9, discount.getSelectedItem().toString());
            stmt.setString(10, pay.getSelectedItem().toString());
            String s1=day.getSelectedItem().toString()+"/"+month.getSelectedItem().toString()+"/"+year.getText();
            int dis=Integer.parseInt(discount.getSelectedItem().toString());
            price=((Integer.parseInt(price)*Integer.parseInt(leas.getText()))-((Integer.parseInt(price)*Integer.parseInt(leas.getText()))*dis/100))+"";             
            stmt.setString(11,price);
            stmt.setString(12,"no");
            stmt.executeUpdate();
            editCarStatus();
            String show="saved *_- \nthe price is : "+price;
            JOptionPane.showMessageDialog(this,show);
                          }catch(Exception e){
                              System.out.println(e);
                          }}else  JOptionPane.showMessageDialog(null, "The car is not available");  
                          }else
                             JOptionPane.showMessageDialog(null, "The Licence number is not available at the store");                   
               }else
                       JOptionPane.showMessageDialog(null, "The ID number is duplicated but not for the same person");
                
            }else
              JOptionPane.showMessageDialog(null, "There is an error in the ID number");                     
                
            }else{
                JOptionPane.showMessageDialog(null, "There is an error in the phone number");
            } 
        }else
          JOptionPane.showMessageDialog(null, "One of the fields is empty");   
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    name.setText("");
    id.setText("");
    phone.setText("");
    lic_num.setText("");
    adress.setText("");
    data.setText("");
    leas.setText("");
    ch_num.setText("");
    year.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        setToolTipText("According to the number of rental days");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        setToolTipText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void leasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasMouseEntered
       setToolTipText("According to the number of rental days");    // TODO add your handling code here:
    }//GEN-LAST:event_leasMouseEntered

    private void leasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasMouseExited
      setToolTipText("");    // TODO add your handling code here:
    }//GEN-LAST:event_leasMouseExited

    private void lic_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lic_numKeyTyped
    if(lic_num.getText().length()>=7){
      evt.consume();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_lic_numKeyTyped
    boolean isNotEmptyChek(){
        if(name.getText().equals("")||id.getText().equals("")||phone.getText().equals("")||lic_num.getText().equals("")||adress.getText().equals("")||data.getText().equals("")||leas.getText().equals("")
           ||ch_num.getText().equals("")||year.getText().equals(""))
            return false;
        return true;
    }
     boolean isNotEmptyCash(){
        if(name.getText().equals("")||id.getText().equals("")||phone.getText().equals("")||lic_num.getText().equals("")||adress.getText().equals("")||data.getText().equals("")||leas.getText().equals("")
          )
            return false;
        return true;
    }
    boolean validReturnCheck(int day , int month, int year){
     if(year==Calendar.getInstance().get(Calendar.YEAR)) {
         if(month==(Calendar.getInstance().get(Calendar.MONTH)+1)){
           if(day>=Calendar.getInstance().get(Calendar.DAY_OF_MONTH)){
               return true;
           }else
               return false;
         }else if(month>Calendar.getInstance().get(Calendar.MONTH))
             return true;
         else return false;
     }else if(year>Calendar.getInstance().get(Calendar.YEAR)) 
         return true;
     else return false;
    }
    boolean validDate(int day,int month,int year){
      if((month==4||month==6||month==9||month==11)){
          if(day<=30)
          return true;
      }else if(month==2){
          if(year%4==0&&year!=2000){
              if(day<=29)return true;
          }else
              if(day<=28)
                  return true;
      }else 
          return true;
      
     return false;
    }
    boolean chekPhone(String phon){
        if(phon.length()!=10)return false;
        if(phon.substring(0,3).equals("059")||phon.substring(0,3).equals("056"))
            return true;
        return false;
    }
    boolean NotrepeatID(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM user WHERE user_id=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, id.getText());

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String nam = rs.getString("name");
                if(!nam.equals(name.getText()))
                    return false;
            }
            return true;
        } catch (Exception e) {

        }
        return true;
    }
    boolean NotrepeatChek(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM user WHERE chek_num=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, ch_num.getText());

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                    return false;
            }
            return true;
        } catch (Exception e) {

        }
        return true;
    }
     String repeatLic_plate(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM car WHERE lic_plate=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, lic_num.getText());

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String nam = rs.getString("price");
                return nam;
            }
            return null;
        } catch (Exception e) {

        }
        return null;
    }
     boolean chekCar(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM car WHERE lic_plate=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, lic_num.getText());

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String nam = rs.getString("status");
                if(nam.equals("Effective"))
                    return true;
                
            }
            return false;
        } catch (Exception e) {

        }  
        return false;
     }
     void editCarStatus(){
         try{
            String[]arr=new String[11];
             Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sql = "SELECT * FROM car WHERE lic_plate=?";        
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1,lic_num.getText());
    ResultSet rs = ps.executeQuery();
    while (rs.next())
    {
    arr[0]=rs.getString("name");
    arr[1]=rs.getString("company");
    arr[2]=rs.getString("fax_num");
    arr[3]=rs.getString("type");
    arr[4]=rs.getString("lic_plate");
    arr[5]=rs.getString("ensurance");
    arr[6]="rented";
    arr[7]=rs.getString("color");
    arr[8]=rs.getString("description");
    arr[9]=rs.getString("price");
    arr[10]=rs.getString("year_manu");
    }
           //حدف سيارة
           String string="delete from car where lic_plate=?";
           PreparedStatement s=con.prepareStatement(string);
           s.setString(1,lic_num.getText());
           s.execute();
           //اضافه سيارة
           String sl = "INSERT INTO car(name,company,fax_num,type,lic_plate,ensurance,status,color,description,price,year_manu) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sl);
            stmt.setString(1,arr[0]);
            stmt.setString(2,arr[1]);
            stmt.setString(3,arr[2]);
            stmt.setString(4,arr[3]);
            stmt.setString(5,arr[4]);
            stmt.setString(6,arr[5]);
            stmt.setString(7,arr[6]);
            stmt.setString(8,arr[7]);
            stmt.setString(9,arr[8]);
            stmt.setString(10,arr[9]);
            stmt.setString(11,arr[10]);
            stmt.executeUpdate(); 
         }catch(Exception e){
             
         }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JComboBox<String> age;
    private javax.swing.JTextField ch_num;
    private javax.swing.JTextField data;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> discount;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField leas;
    private javax.swing.JTextField lic_num;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> pay;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
