package presintationmohamadghaneem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import AppPackage.AnimationClass;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;

/**
 *
 * @author Huthaifa J Salman
 */
public class Logo extends javax.swing.JFrame {

    static int secondpassed = 0;
    Timer myTimer = new Timer();
    TimerTask task = new TimerTask() {
        
        public void run() {
            secondpassed++;
            if (secondpassed == 5) {
                dispose();
                new Main().setVisible(true);
            }
        }
    };

    /**
     * Creates new form Logo
     */
    public Logo() {
        myTimer.scheduleAtFixedRate(task, 1000, 1000);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        AnimationClass anim = new AnimationClass();

        //upper from left
        anim.jLabelXRight(Upper.getX(), 80, 3, 1, Upper);

        //lower from left
        anim.jLabelXLeft(Lower.getX(), 80, 3, 1, Lower);

        //loading bar
        anim.jLabelXRight(LoadingBar.getX(), 0, 3, 1, LoadingBar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lower = new javax.swing.JLabel();
        Upper = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(475, 295));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        Lower.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/logoUnder.png"))); // NOI18N
        getContentPane().add(Lower);
        Lower.setBounds(470, 160, 340, 80);

        Upper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/logoUpper.png"))); // NOI18N
        getContentPane().add(Upper);
        Upper.setBounds(-300, 50, 350, 90);

        LoadingBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/LoadingBar.png"))); // NOI18N
        LoadingBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoadingBarMousePressed(evt);
            }
        });
        getContentPane().add(LoadingBar);
        LoadingBar.setBounds(-480, 280, 500, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/logoBack.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, -60, 550, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadingBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadingBarMousePressed
        
    }//GEN-LAST:event_LoadingBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingBar;
    private javax.swing.JLabel Lower;
    private javax.swing.JLabel Upper;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
