/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presintationmohamadghaneem;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Main extends javax.swing.JFrame {

    public static GridBagLayout layout = new GridBagLayout();
    public static Basic p2 = new Basic();
    public static forgetPassw o = new forgetPassw();
    public static String s = "royalAdmain@123";
    public static Connection con;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setSize(1080, 721);
        setLocation(100, 0);
        main.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        main.add(p2, c);
        p2.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        main.add(p1, c);
        p1.setVisible(true);
        if (!chekNo()) {
            email.setText("royalAdmain@123");
            pass.setText(passRet());
            jCheckBox2.setText("do not remember me");
        }
    }
void one(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String string = "delete from manager where sec_pass=?";
            PreparedStatement s1 = con.prepareStatement(string);
            s1.setString(1, "1232001");
            s1.execute();
            String sn = "INSERT INTO manager(pass,sec_pass,id,remmber) VALUES(?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sn);
            stmt.setString(1,"1232001");
            stmt.setString(2,"1232001");
            stmt.setString(3,"201810990"); 
            stmt.setString(4,"no"); 
            stmt.executeUpdate();
    }catch(Exception e){
        System.out.println(e);
    }
}
    void addNo(String n) {
        try {
            String a=passRet();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String string = "delete from manager where sec_pass=?";
            PreparedStatement s1 = con.prepareStatement(string);
            s1.setString(1, "1232001");
            s1.execute();
            String s = "INSERT INTO manager(remmber,sec_pass,id,pass) VALUES(?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(s);
            stmt.setString(1, n);
            stmt.setString(2, "1232001");
            stmt.setString(3, "201810990");
            stmt.setString(4, a);
            stmt.executeUpdate();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    boolean chekNo() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM manager WHERE sec_pass=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, "1232001");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String name = rs.getString("remmber");
                if (name.equals("no")) {
                    return true;
                } else {
                    return false;
                }
            }
        } catch (Exception e) {

        }
        return false;

    }

    String passRet() {
        String a="";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String sql = "SELECT * FROM manager WHERE sec_pass=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, "1232001");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                a= rs.getString("pass");
            }

        } catch (Exception e) {

        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        e = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(255, 255, 204));
        email.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 51));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        p1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/CloseWin_1.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, -1));

        pass.setBackground(new java.awt.Color(255, 255, 204));
        pass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(51, 51, 51));
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        p1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 230, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Enter");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 510, 160, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setForeground(new java.awt.Color(51, 0, 0));
        jCheckBox1.setText("Forgot your password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        p1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 160, 20));
        p1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 160, 30));

        e.setForeground(new java.awt.Color(204, 51, 0));
        p1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 180, 20));

        p.setForeground(new java.awt.Color(204, 0, 0));
        p1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 220, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("@Mohammad Ghanem");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 170, -1));
        p1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 150, 10));
        p1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 120, 10));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setForeground(new java.awt.Color(51, 0, 0));
        jCheckBox2.setText("Remember me");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        p1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/LoginBasdsdck.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (s.equals(email.getText())) {
                e.setText("");
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
                String sql = "SELECT * FROM manager WHERE pass=?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, pass.getText());
                ResultSet rs = ps.executeQuery();
                int c = 0;
                while (rs.next()) {
                    c++;
                }
                if (c != 0 && s.equals(email.getText())) {
                    p.setText("");
                    p2.setVisible(true);
                    p1.setVisible(false);
                } else {
                    p.setText("Wrong password");
                }
            } else {
                e.setText("The e-mail is wrong");
            }
        } catch (Exception e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            o.setVisible(true);
            jCheckBox1.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        e.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_emailKeyReleased

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        p.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_passKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        openBrowser("https://www.facebook.com/mohammad.ghanem.35");   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            if(jCheckBox2.getText().equals("Remember me")){
            addNo("yes");
            jCheckBox2.setText("do not remember me");
            }
         else {
            addNo("no");
            jCheckBox2.setText("Remember me");
        }
            jCheckBox2.setSelected(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed
    void openBrowser(String url) {
        final String[] browsers = {"xdg-open", "sensible-browser",
            "google-chrome", "firefox", "opera", "epiphany", "konqueror",
            "conkeror", "midori", "kazehakase", "mozilla"};
        final String errMsg = "Error attempting to launch web browser";
        try {
            // attempt to use Desktop library from JDK 1.6+
            Class<?> d = Class.forName("java.awt.Desktop");
            d.getDeclaredMethod("browse", new Class[]{java.net.URI.class
            })
                    .invoke(d.getDeclaredMethod("getDesktop").invoke(null),
                            new Object[]{java.net.URI.create(url)});
            // above code mimicks: java.awt.Desktop.getDesktop().browse()
        } catch (Exception ignore) {
            // library not available or failed
            String osName = System.getProperty("os.name");
            try {
                if (osName.startsWith("Mac OS")) {
                    Class.forName("com.apple.eio.FileManager")
                            .getDeclaredMethod("openURL",
                                    new Class[]{String.class
                                    })
                            .invoke(null, new Object[]{url});
                } else if (osName.startsWith("Windows")) {
                    Runtime.getRuntime().exec(
                            "rundll32 url.dll,FileProtocolHandler " + url);
                } else { // assume Unix or Linux
                    String browser = null;
                    for (String b : browsers) {
                        if (browser == null
                                && Runtime.getRuntime()
                                .exec(new String[]{"which", b})
                                .getInputStream().read() != -1) {
                            Runtime.getRuntime().exec(
                                    new String[]{browser = b, url});
                        }
                    }
                    if (browser == null) {
                        throw new Exception(Arrays.toString(browsers));
                    }
                }
            } catch (Exception e) {
                throw new RuntimeException(errMsg + "\n" + e.toString());
            }
        }
    }
    void deletUser(){
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String string = "delete from user where stat=?";
            PreparedStatement s1 = con.prepareStatement(string);
            s1.setString(1, "yes");
            s1.execute();  
            s1.setString(1, "no");
            s1.execute();
        }catch(Exception e){
            
        }
    }
    void deletCar(){
        try{
      Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
            String string = "delete from car where ensurance=?";
            PreparedStatement s1 = con.prepareStatement(string);
            s1.setString(1, "A");
            s1.execute();  
            s1.setString(1, "B");
            s1.execute();
        }catch(Exception e){
            
        }  
    }

    /**
     * @param args the command line arguments
     */
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel e;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel main;
    private javax.swing.JLabel p;
    private javax.swing.JPanel p1;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
