/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presintationmohamadghaneem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class ShowUser extends javax.swing.JPanel {
public static Connection con;

    /**
     * Creates new form ShowUser
     */
    public ShowUser() {
        initComponents();
         jTable1.setShowVerticalLines(true);
        jTable1.setShowHorizontalLines(true);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(232,57,95));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new Color(232,57,95));
    }
    void bild(){
          DefaultTableModel nt = (DefaultTableModel) jTable1.getModel();
           for(;nt.getRowCount()>0;){
           nt.removeRow(0);
           }
        try{
             Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/com_car?zeroDateTimeBehavior=convertToNull", "root", "");
    String sql = "SELECT * FROM user WHERE stat=?";        
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1,"no");
    ResultSet rs = ps.executeQuery();
    while (rs.next())
    {
        if(rs.getString("pay_method").equals("Check"))
           nt.addRow(new Object[]{rs.getString("name"),rs.getString("age"),rs.getString("user_id"),rs.getString("phone"),rs.getString("licence"),rs.getString("address"),rs.getString("received_data"),rs.getString("lease"),rs.getString("discount"),rs.getString("pay_method"),rs.getString("chek_num"),rs.getString("receive_chek"),rs.getString("amount")});
           else
           nt.addRow(new Object[]{rs.getString("name"),rs.getString("age"),rs.getString("user_id"),rs.getString("phone"),rs.getString("licence"),rs.getString("address"),rs.getString("received_data"),rs.getString("lease"),rs.getString("discount"),rs.getString("pay_method"),"----","----",rs.getString("amount")});
            
    }
    ////////////yes
     ps.setString(1,"yes");
    ResultSet rs1 = ps.executeQuery();
    while (rs1.next())
    {
        if(rs1.getString("pay_method").equals("Check"))
           nt.addRow(new Object[]{rs1.getString("name"),rs1.getString("age"),rs1.getString("user_id"),rs1.getString("phone"),rs1.getString("licence"),rs1.getString("address"),rs1.getString("received_data"),rs1.getString("lease"),rs1.getString("discount"),rs1.getString("pay_method"),rs1.getString("chek_num"),rs1.getString("receive_chek"),rs1.getString("amount")});
           else
           nt.addRow(new Object[]{rs1.getString("name"),rs1.getString("age"),rs1.getString("user_id"),rs1.getString("phone"),rs1.getString("licence"),rs1.getString("address"),rs1.getString("received_data"),rs1.getString("lease"),rs1.getString("discount"),rs1.getString("pay_method"),"----","----",rs1.getString("amount")});
            
    }
    
        }catch(Exception e){
            System.out.println(e);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("List of all customers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 520, 50));

        jSeparator1.setBackground(new java.awt.Color(120, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 490, 20));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "ID Customer", "Phone Num", "Licence Num", "Address", "Received data", "Duration of lease", "Discount", "pay_method", "Chek_number", "Receive chek", "Amount"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(102, 0, 0));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 780, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presintationmohamadghaneem/ازرق_1.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
